### ISSUE TITLE
I never receive the confirmation email

### ISSUE THREAD

**Issue by giovsta** [yassine20011/crispy-giggle#2]
I tested the emails and found them to be working, but Meta seems to be blocking confirmation emails to the created addresses, so I think you need to change the creation system or this script is pointless if one cannot get the confirmation email.

Let me know in case I need to change something on my side

**Comment by yassine20011** [comment]
Yes, it has been a while since I created this it was working fine using this API, but I think meta does not send the confirmation email.

The solution I can give you is to test an API manually to see if it works for you and then change the python script.

1. Open an Incognito tab 
2. Go to the signup then try like an average person to create an IG account using a different API or a website that proved 10min emails(in this case you need to scrape the website).
4. If you got the confirmation email, Now you can start changing the script 

Hopefully, this helps, have a good day.

**Comment by giovsta** [comment]
I cannot find any temporary email service that actually works with Instagram. Thank you anyway for your help
